### ISSUE TITLE
Add Support for Python 3.12

### ISSUE THREAD

**Issue by arossi07** [understand-ai/uai_openlabel#6]
Since this is a dependency of aveas_openlabel, to support Python 3.12, this repo also needs to support 3.12.

**Comment by monoclecat** [comment]
That's right. If you'd like to work on this, please add the 3.12 support to the Github Actions workflows as well. Otherwise we can't test code changes on 3.12 automatically before merging.

**Comment by monoclecat** [comment]
#7

**Comment by monoclecat** [comment]
Added in release v0.3.8 
https://github.com/understand-ai/uai_openlabel/releases/tag/v0.3.8
